from enum import Enum
from typing import TYPE_CHECKING, Protocol

from PySide6.QtCore import QSettings
from PySide6.QtGui import QFont

if TYPE_CHECKING:
	from components.sticky_note import StickyNote

class PlatformType(Enum):
	NativeX11 = 1,
	XWayland = 2,
	Wayland = 3,


class NotesProtocol(Protocol):
	def set_notes_visible(visible: bool): ...
	def are_notes_visible() -> bool: ...
	def delete_note(note: "StickyNote"): ...
	def on_note_sent_to_front(note: "StickyNote"): ...
	def is_quitting() -> bool: ...
	def get_settings() -> QSettings: ...
	def get_app_font() -> QFont: ...
	def get_monospace_font() -> QFont: ...
	def get_menu_font() -> QFont: ...
	def get_platform_type() -> PlatformType: ...


