from typing import Protocol, TYPE_CHECKING

from PySide6.QtCore import QSettings
from PySide6.QtGui import QFont

if TYPE_CHECKING:
	from components.sticky_note import StickyNote


# NOTE: Could use signals for these..
class NotesProtocol(Protocol):
	def delete_note(note: StickyNote): ...
	def on_note_sent_to_front(note: StickyNote): ...
	def is_quitting() -> bool: ...
	def get_settings() -> QSettings: ...
	def get_monospace_font() -> QFont: ...
	def get_menu_font() -> QFont: ...

